# Generated by Django 5.2.6 on 2025-09-06 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comerciante',
            options={'ordering': ['nome_salao'], 'verbose_name': 'Proprietário', 'verbose_name_plural': 'Proprietários'},
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='comerciante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='agendamento.comerciante', verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='comerciante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='agendamento.comerciante', verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo do Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='nome_salao',
            field=models.CharField(help_text='Nome fantasia do estabelecimento', max_length=200, verbose_name='Nome do Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='comerciante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='agendamento.comerciante', verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='comerciante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='agendamento.comerciante', verbose_name='Proprietário'),
        ),
    ]
